[project]
name = "cqrs-ecommerce-webapp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.14"
dependencies = [
    "alembic>=1.18.4",
    "asyncpg>=0.31.0",
    "automium-web",
    "fastapi>=0.135.2",
    "pydantic[email]>=2.12.5",
    "pydantic-settings>=2.13.1",
    "python-dotenv>=1.2.2",
    "sqlalchemy>=2.0.48",
    "uvicorn[standard]>=0.42.0",
    "email-validator>=2.3.0",
    "bcrypt>=5.0.0",
    "pylint>=4.0.5",
    "elasticsearch[async]>=9.3.0",
    "faststream[cli,kafka]>=0.6.7",
    "cachetools>=7.0.5",
    "httpx>=0.28.1",
]
